######################## default configuration ####################
# baseURL = "https://navicarenow.de"
baseUrl = "https://justinguese.github.io/website-hugo-navicarenow"
title = "NavicareNow"
theme = "wallet-hugo"
# post pagination
pagination.pagerSize = "6"
# post excerpt
summaryLength = "10"
# disable language
defaultContentLanguage="de"
disableLanguages = [] # desable language from here
# Image Processing Config
[imaging]
quality = 100


########################### Services #############################
[services]
[services.googleAnalytics]
ID = 'G-MEASUREMENT_ID' # see https://gohugo.io/templates/internal/#configure-google-analytics

[services.disqus]
shortname = 'navicarenow' # we use disqus to show comments in blog posts . To install disqus please follow this tutorial https://portfolio.peter-baumgartner.net/2017/09/10/how-to-install-disqus-on-hugo/


############################# Outputs ##############################
[outputs]
home = ["HTML", "RSS", "JSON", "WebAppManifest"]

[markup]
[markup.goldmark.renderer]
unsafe = true

[mediaTypes]
[mediaTypes."application/manifest+json"]
suffixes = ["webmanifest"]

[mediaTypes."text/netlify"]
delimiter = ""
suffixes = [""]

[outputFormats]
[outputFormats.WebAppManifest]
mediaType = "application/manifest+json"
rel = "manifest"
