# main menu

[[main]]
name = "Für Pflegeheime"
url = "fuer-pflegeheime/"
weight = 1

[[main]]
name = "Über uns"
url = "about/"
weight = 2

[[main]]
name = "Services"
url = "services/"
weight = 3

[[main]]
parent = "Services"
name = "Zentraler Informations-Hub"
url = "services/zentraler-informations-hub/"
weight = 1


[[main]]
parent = "Services"
name = "Community-Schulungen"
url = "services/community-schulungen/"
weight = 2

[[main]]
parent = "Services"
name = "Digitale Pflegeakte"
url = "services/digitale-pflegeakte/"
weight = 3

[[main]]
parent = "Services"
name = "Interaktiver Alltagshelfer"
url = "services/interaktiver-alltagshelfer/"
weight = 4

[[main]]
parent = "Services"
name = "Personalisierte Beratung"
url = "services/personalisierte-beratung/"
weight = 5

[[main]]
name = "FAQ"
url = "faq/"
weight = 4


[[main]]
name = "Kontakt"
url = "kontakt/"
weight = 5

[[main]]
name = "Blog"
url = "blog/"
weight = 5

[[main]]
name = "Legal"
url = "#"
weight = 7

[[main]]
parent = "Legal"
name = "AGB"
url = "legal/terms-conditions/"
weight = 1

[[main]]
parent = "Legal"
name = "Datenschutzerklärung"
url = "legal/privacy-policy/"
weight = 2

[[main]]
parent = "Legal"
name = "Impressum"
url = "legal/imprint/"
weight = 3


################################### Footer Menu #####################################
[[footer]]
name = "Terms & Conditions"
url = "legal/terms-conditions/"

[[footer]]
name = "Privacy Policy"
url = "legal/privacy-policy/"


[[about]]
name = "Unsere Geschichte"
url = "about/"

[[about]]
name = "Team"
url = "about/"

[[about]]
name = "Careers"
url = "/kontakt"


[[help]]
name = "FAQs"
url = "faq/"

[[help]]
name = "Kontakt"
url = "/kontakt"
